name = "dtl-site"
type = "webpack"
account_id = "1b78890bce31a035b4487e68b44f0884"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "dist",entry-point = "workers-site"}
compatibility_date = "2022-03-16"
